name: Github Release

on:

jobs:
  Release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Create a Release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: Release